// ─────────────────────────────────────────────────────────────
//  controllers/keyController.js  —  Power Locker MDM
//  Key Generation, Transfer & Ledger System
//
//  ✅ HIERARCHY RULES:
//  super_admin      → Unlimited generate, kisi ko bhi bhej sakta hai
//  super_distributor → Sirf apne distributors ko transfer kar sakta hai
//  distributor       → Apne sub_distributor + retailer ko transfer
//  sub_distributor   → Sirf apne retailers ko transfer
//  retailer          → Transfer nahi kar sakta (device enroll pe debit hota hai)
//
//  ✅ LEDGER:
//  Sender ka balance DEBIT hota hai (admin ke alawa)
//  Receiver ka balance CREDIT hota hai
//  Dono ke records ledger mein aate hain
// ─────────────────────────────────────────────────────────────
const User              = require('../models/User');
const WalletTransaction = require('../models/WalletTransaction');
const Device            = require('../models/Device');

// ══════════════════════════════════════════════════════════
//  Hierarchy: kaun apne neeche kisko transfer kar sakta hai
// ══════════════════════════════════════════════════════════
const CAN_SEND_TO = {
  super_admin:       ['super_distributor', 'distributor', 'sub_distributor', 'retailer'],
  super_distributor: ['distributor'],
  distributor:       ['sub_distributor', 'retailer'],
  sub_distributor:   ['retailer'],
  retailer:          [],
};

// ══════════════════════════════════════════════════════════
//  Helper: wallet balance update
// ══════════════════════════════════════════════════════════

// Universal key — koi type nahi, sabka ek hi balance
// 'running_key' = universal key balance field
const FIELD_MAP = {
  android:     'runningKeyBalance',   // alias — same field
  running_key: 'runningKeyBalance',   // primary
  iphone:      'runningKeyBalance',   // alias — same field
};

const getField = (keyType = 'running_key') => {
  const f = FIELD_MAP[keyType] || 'runningKeyBalance';
  return f;
};


const updateBalance = async (userId, keyType, amount, type) => {
  const field = getField(keyType);
  const user  = await User.findById(userId);
  if (!user) throw new Error('User not found');

  const before = user[field] || 0;
  if (type === 'debit' && before < amount)
    throw new Error(`Insufficient balance. Available: ${before}, Required: ${amount}`);

  user[field] = type === 'debit' ? before - amount : before + amount;
  await user.save();
  return { before, after: user[field] };
};

// ══════════════════════════════════════════════════════════
//  🔑 SUPER ADMIN — Unlimited Key Generation
//  Admin ka balance deduct NAHI hota
// ══════════════════════════════════════════════════════════

// @desc   Admin: kisi bhi user ko unlimited keys do
// @route  POST /api/keys/generate
// @access super_admin only
const generateKeys = async (req, res) => {
  try {
    const { userId, keyType, amount, description } = req.body;
    if (!userId || !keyType || !amount)
      return res.status(400).json({ success: false, message: 'userId, keyType, amount required' });

    const { before, after } = await updateBalance(userId, keyType, Number(amount), 'credit');

    await WalletTransaction.create({
      userId,
      type:          'credit',
      keyType,
      amount:        Number(amount),
      balanceBefore: before,
      balanceAfter:  after,
      description:   description || `Generated by Super Admin`,
      createdBy:     req.user._id,
      note:          'admin_generate', // admin balance deduct nahi hua
    });

    const target = await User.findById(userId).select('name email role');
    res.json({
      success: true,
      message: `✅ ${amount} ${keyType} keys generated for ${target?.name}`,
      balance: after,
      user:    target,
    });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// @desc   Admin: apne liye keys generate karo (unlimited)
// @route  POST /api/keys/generate-self
// @access super_admin only
const generateSelf = async (req, res) => {
  try {
    const { keyType, amount, description } = req.body;
    if (!keyType || !amount)
      return res.status(400).json({ success: false, message: 'keyType, amount required' });

    const { before, after } = await updateBalance(req.user._id, keyType, Number(amount), 'credit');

    await WalletTransaction.create({
      userId:        req.user._id,
      type:          'credit',
      keyType,
      amount:        Number(amount),
      balanceBefore: before,
      balanceAfter:  after,
      description:   description || 'Self generated by Super Admin',
      createdBy:     req.user._id,
      note:          'admin_generate',
    });

    res.json({ success: true, message: `✅ ${amount} ${keyType} keys added to your wallet`, balance: after });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// @desc   Admin: multiple users ko ek saath credit
// @route  POST /api/keys/bulk-credit
// @access super_admin only
// @body   { users: [{ userId, keyType, amount }], description }
const bulkCredit = async (req, res) => {
  try {
    const { users, description } = req.body;
    if (!Array.isArray(users) || users.length === 0)
      return res.status(400).json({ success: false, message: 'users array required' });

    const results = [];
    for (const { userId, keyType, amount } of users) {
      try {
        const { before, after } = await updateBalance(userId, keyType, Number(amount), 'credit');
        await WalletTransaction.create({
          userId, type: 'credit', keyType, amount: Number(amount),
          balanceBefore: before, balanceAfter: after,
          description: description || 'Bulk credit by admin',
          createdBy: req.user._id,
          note: 'admin_generate',
        });
        results.push({ userId, success: true, balance: after });
      } catch (err) {
        results.push({ userId, success: false, error: err.message });
      }
    }

    const successCount = results.filter(r => r.success).length;
    res.json({ success: true, message: `${successCount}/${users.length} users credited`, results });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   Admin: exact balance set karo (override)
// @route  PUT /api/keys/set-balance
// @access super_admin only
const setBalance = async (req, res) => {
  try {
    const { userId, keyType, amount } = req.body;
    if (!userId || !keyType || amount === undefined)
      return res.status(400).json({ success: false, message: 'userId, keyType, amount required' });

    const field = getField(keyType);
    const user  = await User.findById(userId);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });

    const before  = user[field];
    user[field]   = Number(amount);
    await user.save();

    await WalletTransaction.create({
      userId, type: 'credit', keyType,
      amount:        Number(amount) - before,
      balanceBefore: before,
      balanceAfter:  Number(amount),
      description:   `Balance set to ${amount} by admin`,
      createdBy:     req.user._id,
      note:          'admin_set',
    });

    res.json({ success: true, message: `Balance set to ${amount}`, balance: user[field] });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ══════════════════════════════════════════════════════════
//  🔄 HIERARCHY-BASED KEY TRANSFER
//  Sender ka balance DEBIT → Receiver ka balance CREDIT
//  Sirf apne direct downline ko transfer ho sakti hai
// ══════════════════════════════════════════════════════════

// @desc   Keys transfer karo apne neeche wale ko
// @route  POST /api/keys/transfer
// @access All roles (hierarchy checked)
// @body   { toUserId, keyType, amount, description }
const transferKeys = async (req, res) => {
  try {
    const { toUserId, keyType, amount, description } = req.body;

    if (!toUserId || !keyType || !amount)
      return res.status(400).json({ success: false, message: 'toUserId, keyType, amount required' });

    if (String(toUserId) === String(req.user._id))
      return res.status(400).json({ success: false, message: 'Apne aap ko transfer nahi kar sakte' });

    const sender   = req.user;
    const receiver = await User.findById(toUserId);

    if (!receiver)
      return res.status(404).json({ success: false, message: 'Receiver user not found' });

    if (!receiver.isActive)
      return res.status(403).json({ success: false, message: 'Receiver ka account inactive hai' });

    // ── Hierarchy check: kya sender is receiver ko bhej sakta hai? ──
    const allowedRoles = CAN_SEND_TO[sender.role] || [];
    if (!allowedRoles.includes(receiver.role))
      return res.status(403).json({
        success: false,
        message: `${sender.role.replace(/_/g, ' ')} → ${receiver.role.replace(/_/g, ' ')} transfer allowed nahi hai`,
        allowedTo: allowedRoles,
      });

    // ── Parent check: sirf apna direct child ──
    // Super admin ke liye ye check skip hota hai
    if (sender.role !== 'super_admin') {
      if (String(receiver.parentId) !== String(sender._id))
        return res.status(403).json({
          success: false,
          message: 'Sirf apne direct downline ko hi transfer kar sakte ho',
        });
    }

    const qty = Number(amount);

    // ── Sender balance check ──
    const field         = getField(keyType);
    const senderBalance = sender[field] || 0;
    if (senderBalance < qty)
      return res.status(400).json({
        success: false,
        message: `Insufficient balance. Aapke paas: ${senderBalance}, Chahiye: ${qty}`,
      });

    // ── Atomic transfer: sender debit → receiver credit ──
    const senderResult   = await updateBalance(sender._id,  keyType, qty, 'debit');
    const receiverResult = await updateBalance(receiver._id, keyType, qty, 'credit');

    const note = `Transfer: ${sender.name} (${sender.role}) → ${receiver.name} (${receiver.role})`;

    // Sender ledger — DEBIT entry
    await WalletTransaction.create({
      userId:        sender._id,
      type:          'debit',
      keyType,
      amount:        qty,
      balanceBefore: senderResult.before,
      balanceAfter:  senderResult.after,
      description:   description || `Transfer to ${receiver.name}`,
      toUserId:      receiver._id,
      createdBy:     sender._id,
      note,
    });

    // Receiver ledger — CREDIT entry
    await WalletTransaction.create({
      userId:        receiver._id,
      type:          'credit',
      keyType,
      amount:        qty,
      balanceBefore: receiverResult.before,
      balanceAfter:  receiverResult.after,
      description:   description || `Received from ${sender.name}`,
      fromUserId:    sender._id,
      createdBy:     sender._id,
      note,
    });

    res.json({
      success:  true,
      message:  `✅ ${qty} ${keyType} keys transferred to ${receiver.name}`,
      sender: {
        name:       sender.name,
        role:       sender.role,
        newBalance: senderResult.after,
      },
      receiver: {
        name:       receiver.name,
        role:       receiver.role,
        newBalance: receiverResult.after,
      },
    });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// ══════════════════════════════════════════════════════════
//  🔑 ADMIN TRANSFER — From any user to their direct child
//  Admin panel se hierarchy-based debit/credit
// ══════════════════════════════════════════════════════════

// @desc   Admin: fromUser ka balance deduct → toUser ko credit
// @route  POST /api/keys/admin-transfer
// @access super_admin only
// @body   { fromUserId, toUserId, amount, description? }
const adminTransfer = async (req, res) => {
  try {
    const { fromUserId, toUserId, amount, description } = req.body;

    if (!fromUserId || !toUserId || !amount)
      return res.status(400).json({ success: false, message: 'fromUserId, toUserId, amount required' });

    if (String(fromUserId) === String(toUserId))
      return res.status(400).json({ success: false, message: 'fromUser aur toUser alag hone chahiye' });

    const sender   = await User.findById(fromUserId);
    const receiver = await User.findById(toUserId);

    if (!sender)   return res.status(404).json({ success: false, message: 'Sender not found' });
    if (!receiver) return res.status(404).json({ success: false, message: 'Receiver not found' });

    // ── Hierarchy check ──────────────────────────────────────
    // super_admin can transfer between ANY two users (Return Key, Credit, etc.)
    // Non-admin: sender → direct child OR child → sender only
    const requesterIsSuperAdmin = req.user.role === 'super_admin';

    if (!requesterIsSuperAdmin) {
      const senderIsParentOfReceiver = String(receiver.parentId) === String(sender._id);
      const receiverIsParentOfSender = String(sender.parentId)   === String(receiver._id);
      const isAncestor = async (ancestorId, descendantId) => {
        let current = await User.findById(descendantId).select('parentId');
        const visited = new Set();
        while (current?.parentId) {
          const pid = String(current.parentId);
          if (pid === String(ancestorId)) return true;
          if (visited.has(pid)) break;
          visited.add(pid);
          current = await User.findById(pid).select('parentId');
        }
        return false;
      };
      const forward = senderIsParentOfReceiver || await isAncestor(sender._id, receiver._id);
      const reverse = receiverIsParentOfSender || await isAncestor(receiver._id, sender._id);
      if (!forward && !reverse) {
        return res.status(403).json({
          success: false,
          message: `${sender.name} aur ${receiver.name} ke beech koi hierarchy relation nahi hai`,
        });
      }
    }
    // super_admin: no hierarchy restriction — can take from anyone


    const qty     = Number(amount);
    const keyType = 'running_key'; // universal

    // ── Balance check ──
    const field         = getField(keyType);
    const senderBalance = sender[field] || 0;
    if (senderBalance < qty)
      return res.status(400).json({
        success: false,
        message: `Insufficient balance. ${sender.name} ke paas: ${senderBalance}, Chahiye: ${qty}`,
      });

    // ── Transfer ──
    const senderResult   = await updateBalance(sender._id,   keyType, qty, 'debit');
    const receiverResult = await updateBalance(receiver._id, keyType, qty, 'credit');

    const note = `Admin Transfer: ${sender.name} (${sender.role}) → ${receiver.name} (${receiver.role})`;

    await WalletTransaction.create({
      userId: sender._id, type: 'debit', keyType, amount: qty,
      balanceBefore: senderResult.before, balanceAfter: senderResult.after,
      description: description || `Transfer to ${receiver.name}`,
      toUserId: receiver._id, createdBy: req.user._id, note,
    });

    await WalletTransaction.create({
      userId: receiver._id, type: 'credit', keyType, amount: qty,
      balanceBefore: receiverResult.before, balanceAfter: receiverResult.after,
      description: description || `Received from ${sender.name}`,
      fromUserId: sender._id, createdBy: req.user._id, note,
    });

    res.json({
      success: true,
      message: `✅ ${qty} keys: ${sender.name} → ${receiver.name}`,
      sender:   { name: sender.name,   role: sender.role,   newBalance: senderResult.after },
      receiver: { name: receiver.name, role: receiver.role, newBalance: receiverResult.after },
    });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// @desc   Admin: parentId ke direct children fetch karo (dropdown ke liye)
// @route  GET /api/keys/children/:parentId
// @access super_admin only
const getChildrenByParent = async (req, res) => {
  try {
    const { parentId } = req.params;
    const children = await User.find({
      parentId,
      isDeleted: false,
      isActive: true,
    }).select('_id name role runningKeyBalance email phone');

    res.json({
      success: true,
      data: children.map(c => ({
        id:      c._id,
        _id:     c._id,
        name:    c.name,
        role:    c.role,
        balance: c.runningKeyBalance || 0,
        email:   c.email,
        phone:   c.phone,
      })),
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   ALL descendants (BFS: children + grandchildren + great-grandchildren)
// @route  GET /api/keys/descendants/:userId
// @access super_admin only
const getDescendantsByUser = async (req, res) => {
  try {
    const { userId } = req.params;
    const descendants = [];
    const queue       = [userId];
    const visited     = new Set([String(userId)]);

    while (queue.length > 0) {
      const currentId = queue.shift();
      const children  = await User.find({
        parentId:  currentId,
        isDeleted: { $ne: true },
        isActive:  true,
      }).select('_id name role runningKeyBalance email phone parentId');

      for (const child of children) {
        const id = String(child._id);
        if (!visited.has(id)) {
          visited.add(id);
          descendants.push(child);
          queue.push(id);
        }
      }
    }

    res.json({
      success: true,
      data: descendants.map(c => ({
        id:      c._id,
        _id:     c._id,
        name:    c.name,
        role:    c.role,
        balance: c.runningKeyBalance || 0,
        email:   c.email,
        phone:   c.phone,
      })),
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};




// @desc   Admin: direct credit (admin se kisi ko, sender deduct nahi)
// @route  POST /api/keys/credit
// @access super_admin only
const creditKeys = async (req, res) => {
  try {
    const { userId, keyType, amount, description } = req.body;
    if (!userId || !keyType || !amount)
      return res.status(400).json({ success: false, message: 'userId, keyType, amount required' });

    const { before, after } = await updateBalance(userId, keyType, Number(amount), 'credit');

    await WalletTransaction.create({
      userId, type: 'credit', keyType, amount: Number(amount),
      balanceBefore: before, balanceAfter: after,
      description:  description || 'Credit by admin',
      createdBy:    req.user._id,
      note:         'admin_credit',
    });

    res.json({ success: true, message: `${amount} ${keyType} keys credited`, balance: after });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// @desc   Debit keys:
//         - Device enroll: logged-in user ka balance deduct (no userId body)
//         - Admin manual:  kisi bhi user ka balance deduct (userId in body, adminOnly)
// @route  POST /api/keys/debit
const debitKey = async (req, res) => {
  try {
    const { keyType, amount = 1, referenceId, description, userId } = req.body;

    // ── Admin manual debit: userId body mein ──
    if (userId) {
      // Only admin can debit someone else
      if (req.user.role !== 'super_admin') {
        return res.status(403).json({
          success: false,
          message: 'Sirf Super Admin kisi aur ka balance deduct kar sakta hai',
        });
      }

      const target = await User.findById(userId);
      if (!target) return res.status(404).json({ success: false, message: 'User not found' });

      const { before, after } = await updateBalance(userId, keyType, Number(amount), 'debit');

      await WalletTransaction.create({
        userId,
        type: 'debit',
        keyType,
        amount: Number(amount),
        balanceBefore: before,
        balanceAfter:  after,
        description:   description || `Manual debit by admin`,
        createdBy:     req.user._id,
        note:          'admin_debit',
      });

      return res.json({
        success: true,
        message: `${amount} ${keyType} keys debited from ${target.name}`,
        balance: after,
        user:    { name: target.name, role: target.role },
      });
    }

    // ── Device enroll debit: apna balance deduct ──
    const { before, after } = await updateBalance(req.user._id, keyType, Number(amount), 'debit');

    await WalletTransaction.create({
      userId:        req.user._id,
      type:          'debit',
      keyType,
      amount:        Number(amount),
      balanceBefore: before,
      balanceAfter:  after,
      description:   description || 'Device enrolled',
      referenceId,
      createdBy:     req.user._id,
    });

    res.json({ success: true, message: 'Key debited', balance: after });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};


// @desc   FOC — Free of cost credit (admin)
// @route  POST /api/keys/credit-foc
const creditFoc = async (req, res) => {
  try {
    const { userId, keyType, amount, description } = req.body;
    const { before, after } = await updateBalance(userId, keyType, Number(amount), 'credit');

    await WalletTransaction.create({
      userId, type: 'credit_foc', keyType, amount: Number(amount),
      balanceBefore: before, balanceAfter: after,
      description: description || 'FOC credit by admin',
      createdBy: req.user._id,
      note: 'admin_foc',
    });

    res.json({ success: true, message: `${amount} FOC keys credited`, balance: after });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// @desc   Apna current balance dekho
// @route  GET /api/keys/balance
const getBalance = async (req, res) => {
  try {
    const user = await User.findById(req.user._id)
      .select('androidBalance runningKeyBalance iphoneBalance name email role');
    res.json({ success: true, balance: user });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ══════════════════════════════════════════════════════════
//  📒 LEDGER — Transaction History
// ══════════════════════════════════════════════════════════

// @desc   Apna ledger dekho | Admin sab dekhe
// @route  GET /api/keys/ledger
const getLedger = async (req, res) => {
  try {
    const { page = 1, limit = 20, keyType, type, from, to } = req.query;

    const isAdmin = req.user.role === 'super_admin';
    const query   = isAdmin ? {} : { $or: [{ userId: req.user._id }, { toUserId: req.user._id }, { fromUserId: req.user._id }] };

    if (keyType) query.keyType = keyType;
    if (type)    query.type    = type;
    if (from || to) {
      query.createdAt = {};
      if (from) query.createdAt.$gte = new Date(from);
      if (to)   query.createdAt.$lte = new Date(new Date(to).setHours(23, 59, 59, 999));
    }

    const total        = await WalletTransaction.countDocuments(query);
    const transactions = await WalletTransaction.find(query)
      .populate('userId',     'name email phone role')
      .populate('createdBy',  'name email role')
      .populate('toUserId',   'name email role')
      .populate('fromUserId', 'name email role')
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(Number(limit));

    const summary = await WalletTransaction.aggregate([
      { $match: isAdmin ? {} : { userId: req.user._id } },
      { $group: { _id: { type: '$type', keyType: '$keyType' }, total: { $sum: '$amount' }, count: { $sum: 1 } } },
    ]);

    res.json({
      success: true, total,
      totalPages:  Math.ceil(total / limit),
      currentPage: Number(page),
      summary,
      data: transactions,
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   All users ledger (admin)
// @route  GET /api/keys/ledger/all
const getLedgerAll = async (req, res) => {
  try {
    const { page = 1, limit = 50, keyType, type, from, to, userId, role } = req.query;
    const query = {};

    if (keyType) query.keyType = keyType;
    if (type)    query.type    = type;
    if (userId)  query.userId  = userId;
    if (from || to) {
      query.createdAt = {};
      if (from) query.createdAt.$gte = new Date(from);
      if (to)   query.createdAt.$lte = new Date(new Date(to).setHours(23, 59, 59, 999));
    }
    if (role) {
      const roleUsers = await User.find({ role }).select('_id');
      query.userId    = { $in: roleUsers.map(u => u._id) };
    }

    const total        = await WalletTransaction.countDocuments(query);
    const transactions = await WalletTransaction.find(query)
      .populate('userId',     'name email phone role company')
      .populate('createdBy',  'name email role')
      .populate('toUserId',   'name email role')
      .populate('fromUserId', 'name email role')
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(Number(limit));

    const totals = await WalletTransaction.aggregate([
      { $match: query },
      { $group: { _id: { type: '$type', keyType: '$keyType' }, total: { $sum: '$amount' }, count: { $sum: 1 } } },
    ]);

    res.json({
      success: true, total,
      totalPages:  Math.ceil(total / limit),
      currentPage: Number(page),
      totals,
      data: transactions,
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   Dashboard stats (admin)
// @route  GET /api/keys/ledger/summary
const getLedgerSummary = async (req, res) => {
  try {
    const { from, to } = req.query;
    const matchDate    = {};
    if (from || to) {
      matchDate.createdAt = {};
      if (from) matchDate.createdAt.$gte = new Date(from);
      if (to)   matchDate.createdAt.$lte = new Date(new Date(to).setHours(23, 59, 59, 999));
    }

    const [byType, byKeyType, daily, topUsers] = await Promise.all([
      WalletTransaction.aggregate([
        { $match: matchDate },
        { $group: { _id: '$type', totalAmount: { $sum: '$amount' }, count: { $sum: 1 } } },
      ]),
      WalletTransaction.aggregate([
        { $match: matchDate },
        { $group: { _id: '$keyType', totalAmount: { $sum: '$amount' }, count: { $sum: 1 } } },
      ]),
      WalletTransaction.aggregate([
        { $match: { createdAt: { $gte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) } } },
        { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, total: { $sum: '$amount' }, count: { $sum: 1 } } },
        { $sort: { _id: 1 } },
      ]),
      WalletTransaction.aggregate([
        { $match: { type: { $in: ['credit', 'credit_foc'] } } },
        { $group: { _id: '$userId', totalReceived: { $sum: '$amount' } } },
        { $sort: { totalReceived: -1 } },
        { $limit: 10 },
        { $lookup: { from: 'users', localField: '_id', foreignField: '_id', as: 'user' } },
        { $unwind: '$user' },
        { $project: { totalReceived: 1, 'user.name': 1, 'user.email': 1, 'user.role': 1 } },
      ]),
    ]);

    res.json({ success: true, byType, byKeyType, daily, topUsers });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   Specific user ledger (admin)
// @route  GET /api/keys/ledger/user/:userId
const getLedgerByUser = async (req, res) => {
  try {
    const { page = 1, limit = 20, keyType, type } = req.query;
    const query = {
      $or: [
        { userId:     req.params.userId },
        { toUserId:   req.params.userId },
        { fromUserId: req.params.userId },
      ],
    };
    if (keyType) query.keyType = keyType;
    if (type)    query.type    = type;

    const total        = await WalletTransaction.countDocuments(query);
    const transactions = await WalletTransaction.find(query)
      .populate('createdBy',  'name role')
      .populate('toUserId',   'name role')
      .populate('fromUserId', 'name role')
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(Number(limit));

    const user = await User.findById(req.params.userId)
      .select('name email role androidBalance runningKeyBalance iphoneBalance');

    res.json({ success: true, total, totalPages: Math.ceil(total / limit), user, data: transactions });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   Apne devices ka key stats
// @route  GET /api/keys/my-keys
const getMyKeys = async (req, res) => {
  try {
    const stats = await Device.aggregate([
      { $match: { retailerId: req.user._id } },
      { $group: { _id: { keyType: '$keyType', status: '$status' }, count: { $sum: 1 } } },
    ]);
    res.json({ success: true, stats });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   Parent se keys request karo
// @route  POST /api/keys/request
const requestKeys = async (req, res) => {
  try {
    const { keyType, amount, description } = req.body;
    if (!keyType || !amount)
      return res.status(400).json({ success: false, message: 'keyType, amount required' });

    await WalletTransaction.create({
      userId:      req.user._id,
      type:        'request',
      keyType,
      amount:      Number(amount),
      status:      'pending',
      description: description || 'Key request',
      createdBy:   req.user._id,
    });
    res.json({ success: true, message: 'Key request submitted' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc   Request approve/reject (admin)
// @route  POST /api/keys/request/approve
const approveKeyRequest = async (req, res) => {
  try {
    const { transactionId, action } = req.body;
    if (!['approve', 'reject'].includes(action))
      return res.status(400).json({ success: false, message: 'action: approve | reject' });

    const tx = await WalletTransaction.findById(transactionId);
    if (!tx || tx.type !== 'request')
      return res.status(404).json({ success: false, message: 'Request not found' });

    if (action === 'approve') {
      const { before, after } = await updateBalance(tx.userId, tx.keyType, tx.amount, 'credit');
      await WalletTransaction.create({
        userId: tx.userId, type: 'credit', keyType: tx.keyType,
        amount: tx.amount, balanceBefore: before, balanceAfter: after,
        description: 'Request approved', createdBy: req.user._id,
        note: 'admin_approve',
      });
      tx.status = 'approved';
    } else {
      tx.status = 'rejected';
    }
    await tx.save();
    res.json({ success: true, message: `Request ${action}d` });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
};

// @desc   Pending requests list (admin)
// @route  GET /api/keys/requests
const getKeyRequests = async (req, res) => {
  try {
    const { status = 'pending', page = 1, limit = 20 } = req.query;
    const query = { type: 'request' };
    if (status !== 'all') query.status = status;

    const total    = await WalletTransaction.countDocuments(query);
    const requests = await WalletTransaction.find(query)
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(Number(limit))
      .populate('userId', 'name email phone role');

    res.json({ success: true, total, data: requests });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

module.exports = {
  // Super Admin — unlimited generation
  generateKeys,
  generateSelf,
  bulkCredit,
  setBalance,
  // Hierarchy transfer (all roles — apne downline ko)
  transferKeys,
  // Standard ops
  creditKeys,
  debitKey,
  creditFoc,
  getBalance,
  // Ledger
  getLedger,
  getLedgerAll,
  getLedgerSummary,
  getLedgerByUser,
  // Other
  getMyKeys,
  requestKeys,
  approveKeyRequest,
  getKeyRequests,
  // Admin hierarchy transfer
  adminTransfer,
  getChildrenByParent,
  getDescendantsByUser,
  // Internal helper
  updateBalance,
};
